#!/bin/bash

# Так мы добавляем возможность установки репозиториев (первая команда), ставим репозиторий твикера
# и устанавливаем его
sudo apt install -y software-properties-commonsudo 
sudo add-apt-repository -y ppa:philip.scott/elementary-tweaks
sudo apt install -y elementary-tweaks

# Устанавливаем программы
sudo apt install -y \
git \
neofetch \
gedit \
ark \
vlc

# Качка и установка
wget https://discord.com/api/download?platform=linux&format=deb 
wget https://dn3.freedownloadmanager.org/6/latest/freedownloadmanager.deb
sudo dpkg -i *.deb
sudo apt install -f -y

# Папирус!
git clone https://github.com/PapirusDevelopmentTeam/papirus-icon-theme.git
cd papirus-icon-theme.git
sudo sh install.sh
cd

# Удаляем мусор
sudo rm *.deb
sudo rm -r papirus-icon-theme.git

# Все
echo 'Я все, хозяин!'
